{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-configuration-processor",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.5.jar",
          "url": "spring-boot-configuration-processor-3.3.5.jar",
          "size": 129935,
          "sha512": "fc660acd58bbc8fa3d5b195be3fc18952bb68c89223d63bc69ec3f11d1f2c8bf3987d250e608bad594deffe20e11496e53c4b2f09fa50b83098267adabbf3896",
          "sha256": "81c398495000ebc54c0853647fb252fb6c0f94e25faaf913088bbeabe7acc908",
          "sha1": "33b9d3f722281e8f9dbbd284135ee8b9909c42cf",
          "md5": "32b01a1f304ac4697006763790ca2e6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.5.jar",
          "url": "spring-boot-configuration-processor-3.3.5.jar",
          "size": 129935,
          "sha512": "fc660acd58bbc8fa3d5b195be3fc18952bb68c89223d63bc69ec3f11d1f2c8bf3987d250e608bad594deffe20e11496e53c4b2f09fa50b83098267adabbf3896",
          "sha256": "81c398495000ebc54c0853647fb252fb6c0f94e25faaf913088bbeabe7acc908",
          "sha1": "33b9d3f722281e8f9dbbd284135ee8b9909c42cf",
          "md5": "32b01a1f304ac4697006763790ca2e6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.5-javadoc.jar",
          "url": "spring-boot-configuration-processor-3.3.5-javadoc.jar",
          "size": 184365,
          "sha512": "f72325cfb75f1390bc29f6b845070896197febe65b48f3d05b400d9a509f4e5585cd02c0bce981a521ee9a8a6b85b36a7bfd786c67d15df2544ba52595d20f95",
          "sha256": "65dc622b4eccdf18420e7b29856ff249db82faffdf27316adb6101becb08bd72",
          "sha1": "8eb3358a00a54ca71194db682f7c4459af4bc023",
          "md5": "df5258d16eddb0345397d12bacb3f0a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.5-sources.jar",
          "url": "spring-boot-configuration-processor-3.3.5-sources.jar",
          "size": 84200,
          "sha512": "cfc63dc4a193c25c536e71330a05e59f8b9aca9bc4db444b6552ff318e430840cbb0a90126efa8a5fa425676ecf99be0a45eb0bd807bbab3dbb1edd52415f2ac",
          "sha256": "a8353fec1d2f59c5b6b9d1ebf4cb4282d91c8802f52be59b3fdda453eaf36aef",
          "sha1": "f001cf68caf78b8e218a4492dc6f0aa66c54952b",
          "md5": "5ad976e92a33f7be682c92c18f4081cd"
        }
      ]
    }
  ]
}
